<?php

namespace Mollie\Subscriptions\Test\Fakes\Service\Mollie;

use Mollie\Api\MollieApiClient;
use Mollie\Subscriptions\Service\Mollie\MollieSubscriptionApi;

class MollieSubscriptionApiFake extends MollieSubscriptionApi
{
    private MollieApiClient $instance;

    public function loadByApiKey(string $apiKey): MollieApiClient
    {
        if ($this->instance) {
            return $this->instance;
        }

        return parent::loadByApiKey($apiKey); // TODO: Change the autogenerated stub
    }

    public function loadByStore(?int $storeId = null): MollieApiClient
    {
        if ($this->instance) {
            return $this->instance;
        }

        return parent::loadByStore($storeId); // TODO: Change the autogenerated stub
    }

    public function setInstance(MollieApiClient $instance): void
    {
        $this->instance = $instance;
    }
}
